inventory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('inventoryapp/', include('inventoryapp.urls')),
    path('admin/', admin.site.urls),
]

inventoryapp/urls.py
from django.urls import path

from . import views

app_name = 'inventoryapp'
urlpatterns = [
    # ex: /InventoryApp/
    path('', views.list, name='list'),
    # ex: 
    path('modify/<int:product_ref>/', views.modify, name='modify'),
    # ex: 
    path('productForm/', views.addProductForm, name='productForm')
]

inventoryapp/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    reference = models.AutoField(primary_key=True)
    product_gtin = models.BigIntegerField()
    expiry_date = models.DateField()

    def __str__(self):
        return self.product_gtin

    def __eq__(self, other):
        if self.product_gtin == other.product_gtin:
            return True
        else:
            return False

    def __ge__(self, other):
        if self.product_gtin > other.product_gtin:
            return True
        else:
            return False

    def __le__(self, other):
        if self.product_gtin > other.product_gtin:
            return True
        else:
            return False

inventoryapp/forms.py
import datetime

from django import forms
from django.forms.widgets import DateInput
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

class ProductForm(forms.Form):
    product_gtin = forms.CharField(label='Product GTIN', max_length=13, required=True, )
    product_expiry_date = forms.DateField(label='Product Expiry date', widget=DateInput, required=True, error_messages=
        {"invalid" : "Enter the product's expiry date using one of the following formats: YYYY-MM-DD or MM/DD/YYYY or MM/DD/YY"})

    def clean_product_gtin(self):
        clean_gtin = self.cleaned_data['product_gtin']

        # Check if the length of the product's gtin is 13
        if len(clean_gtin) != 13:
            raise ValidationError(_('Invalid product gtin - should be 13 numbers'))

        return clean_gtin

    def clean_product_expiry_date(self):
        clean_expiry_date = self.cleaned_data['product_expiry_date']

        # Check if product is not expired
        if clean_expiry_date < datetime.date.today():
            raise ValidationError(_('Invalid date - product already expired'))

        return clean_expiry_date


class ModifyForm(forms.Form):
    product_expiry_date = forms.DateField(label='New Product\'s Expiry date', widget=DateInput, required=True, error_messages=
        {"invalid" : "Enter the product's expiry date using one of the following formats: YYYY-MM-DD or MM/DD/YYYY or MM/DD/YY"})

    def clean_product_expiry_date(self):
        clean_expiry_date = self.cleaned_data['product_expiry_date']

        # Check if product is not expired
        if clean_expiry_date < datetime.date.today():
            raise ValidationError(_('Invalid date - product already expired'))

        return clean_expiry_date

inventoryapp/views.py
from datetime import date

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Product
from .forms import ProductForm, ModifyForm

def list(request):
    db_products_list = Product.objects.all().order_by('expiry_date')
    products_list = []
    expired_products = []
    
    for product in db_products_list:
        if product not in products_list:
            products_list.append(product)
        elif product in products_list and product.expiry_date < products_list[products_list.index(product)].expiry_date:
            products_list[products_list.index(product)] = product

    for product in products_list:
        if product.expiry_date <= date.today():
            expired_products.append(product)

    context = {'products_list' : products_list, 'expired_products': expired_products}
    return render(request, 'inventoryapp/list.html', context)

def modify(request, product_ref):
    product = get_object_or_404(Product, pk=product_ref)

    if request.method == 'POST':

        form = ModifyForm(request.POST)

        if form.is_valid():
            
            product.expiry_date = form.cleaned_data['product_expiry_date']
            product.save()

            return HttpResponseRedirect(reverse('inventoryapp:list'))
        
    else:
        form = ModifyForm()

    context = {
        'form': form,
        'product': product,
    }
    
    return render(request, 'inventoryapp/modify.html', context)

def addProductForm(request):
    gtin_list = [o.product_gtin for o in Product.objects.all()]

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        form = ProductForm(request.POST)

        if form.is_valid():

            product = Product(product_gtin=form.cleaned_data['product_gtin'], expiry_date=form.cleaned_data['product_expiry_date'])
            productFromDb = Product.objects.filter(pk=product.product_gtin)
            
            if (product.product_gtin in gtin_list) and productFromDb.values('expiry_date') > product.expiry_date:
                Product.objects.filter(pk=product.product_gtin).update(expiry_date=form.cleaned_data['product_expiry_date'])

            else:
                product.save()
            return HttpResponseRedirect(reverse('inventoryapp:list'))

    else:
        form = ProductForm()

    return render(request, 'inventoryapp/productForm.html', {'form': form})

inventoryapp/templates/inventoryapp/list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inventory App</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'InventoryApp/style.css' %}">
</head>

<body>
    <div class="container">
        <h1>List of Products and their expiry dates</h1>
        {% if products_list %}
        <table class="layout display responsive-table">
            <thead>
                <tr>
                    <th>References</th>
                    <th>Product GTIN</th>
                    <th>Product Expiry date</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products_list %}
                <tr>
                    <td class="ref">{{product.reference}}</td>
                    <td class="gtin">{{product.product_gtin}}</td>
                    {% if product not in expired_products %}
                    <td class="date">{{product.expiry_date}}</td>
                    {% else %}
                    <td id="expired_date">{{product.expiry_date}}</td>
                    {% endif %}
                    <td id="actions">
                        <form action="{% url 'inventoryapp:modify' product.reference %}">
                            <input type="submit" value="Modify">
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>No Product is available</p>
        {% endif %}
        <form action="{% url 'inventoryapp:productForm' %}">
            <input type="submit" value="Add a Product">
        </form>
    </div>
</body>

</html>

inventoryapp/templates/inventoryapp/modify.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modify product</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'inventoryapp/style.css' %}">
</head>

<body>
    <div class="container">
        <h1>Modify a Product</h1>
        <ul>
            <li><h3>Reference: </h3><span>{{ product.reference }}</span></li>
            <li><h3>GTIN: </h3><span>{{ product.product_gtin }}</span></li>
            <li><h3>Expiry Date: </h3><span>{{ product.expiry_date }}</span></li>
        </ul>

        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }} <br><br>
            <input type="submit" value="Modify">
        </form>
    </div>
</body>

</html>

inventoryapp/templates/inventoryapp/productForm.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add a Product</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'inventoryapp/style.css' %}">
</head>

<body>
    <div class="container">
        <h1>Add a Product</h1>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }} <br><br>
            <input type="submit" value="Add to Database">
        </form>
    </div>
</body>

</html>